'use client'

import { useEffect, useState } from 'react'
import ReactMarkdown from 'react-markdown'

interface Digest {
  id: string
  date: string
  summary: string
  generatedAt: string
}

export default function StandupCard() {
  const [digest, setDigest] = useState<Digest | null>(null)
  const [isToday, setIsToday] = useState(false)
  const [loading, setLoading] = useState(true)
  const [collapsed, setCollapsed] = useState(false)

  useEffect(() => {
    void (async () => {
      try {
        const res = await fetch('/api/assistant/standup-digest', { credentials: 'include' })
        if (!res.ok) return
        const json = (await res.json()) as {
          data?: { digest: Digest | null; isToday: boolean }
        }
        if (json.data?.digest) {
          setDigest(json.data.digest)
          setIsToday(json.data.isToday)
        }
      } finally {
        setLoading(false)
      }
    })()
  }, [])

  if (loading || !digest) return null

  const date = new Date(digest.date)
  const dateLabel = date.toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'short',
    day: 'numeric',
  })

  return (
    <div className="bg-white border border-black/10 rounded-2xl p-5 mb-6">
      <div className="flex items-center justify-between mb-3">
        <div>
          <h3 className="text-sm font-mono uppercase tracking-widest text-[#1A1A1A]">
            Team standup {isToday ? '· Today' : `· ${dateLabel}`}
          </h3>
          <p className="text-xs text-[#999] mt-0.5">
            Auto-generated by Forgie · {!isToday && 'Last available digest'}
          </p>
        </div>
        <button
          type="button"
          onClick={() => setCollapsed((c) => !c)}
          className="font-mono text-[10px] tracking-widest text-[#999] hover:text-[#1A1A1A] transition-colors"
        >
          {collapsed ? 'EXPAND' : 'COLLAPSE'}
        </button>
      </div>

      {!collapsed && (
        <div className="prose prose-sm max-w-none text-[#1A1A1A] prose-p:my-2 prose-strong:text-[#1A1A1A] prose-strong:font-semibold">
          <ReactMarkdown>{digest.summary}</ReactMarkdown>
        </div>
      )}
    </div>
  )
}
